# Please move this to the root of the project to run Docker

version: '3'
networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
services:
  nodeA:
    image: ghcr.io/anthony2708/websocket-server:latest
    ports:
      - "8080:8080"
    restart: always
    hostname: nodeA
    networks:
      mynet:
        - ipv4_address: 172.10.0.2

  nodeB:
    image: ghcr.io/anthony2708/websocket-server:latest
    ports:
      - "8081:8080"
    restart: always
    hostname: nodeB
    networks:
      mynet:
        - ipv4_address: 172.10.0.3

  nodeC:
    image: ghcr.io/anthony2708/websocket-server:latest
    ports:
      - "8082:8080"
    restart: always
    hostname: nodeC
    networks:
      mynet:
        - ipv4_address: 172.10.0.4
