# Generated by Django 3.2.9 on 2021-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm_admin', '0002_hlvien_vaitro'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaidau',
            name='sodoi_hientai',
            field=models.IntegerField(default=0),
        ),
    ]
