# Generated by Django 3.2.9 on 2021-12-15 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm_admin', '0003_giaidau_sodoi_hientai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doibong',
            name='playing',
        ),
        migrations.AddField(
            model_name='doibong',
            name='playin',
            field=models.ForeignKey(
                default=4325, on_delete=django.db.models.deletion.CASCADE,
                to='fsm_admin.giaidau'),
            preserve_default=False,
        ),
    ]
