# Generated by Django 3.2.9 on 2021-12-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm_admin', '0004_auto_20211215_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='doibong',
            name='playing',
            field=models.BooleanField(default=False),
        ),
    ]
