# Generated by Django 3.2.9 on 2021-12-15 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm_admin', '0006_alter_doibong_playin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAIKHOAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=20)),
                ('ngaysinh', models.DateField()),
                ('gioitinh', models.CharField(max_length=5)),
                ('diachi', models.CharField(max_length=50)),
                ('so_dienthoai', models.CharField(max_length=15)),
                ('ma_taikhoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
