# Generated by Django 3.2.9 on 2021-12-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm_admin', '0008_chitiettrandau_trandau_trongtai_xephang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xephang',
            name='banthang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xephang',
            name='hieuso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xephang',
            name='so_diem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xephang',
            name='so_tran',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xephang',
            name='thephat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xephang',
            name='thuhang',
            field=models.IntegerField(default=0),
        ),
    ]
