# Generated by Django 3.2.9 on 2021-12-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm_admin', '0010_giaidau_is_arranged'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitiettrandau',
            name='tinhchat',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chitiettrandau',
            name='ma_doiA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DoiA', to='fsm_admin.doibong'),
        ),
        migrations.AlterField(
            model_name='chitiettrandau',
            name='ma_doiB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DoiB', to='fsm_admin.doibong'),
        ),
    ]
