# Generated by Django 3.2.9 on 2021-12-18 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm_admin', '0011_auto_20211217_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doibong',
            name='playin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsm_admin.giaidau'),
        ),
    ]
