image: hashicorp/terraform:latest

pipelines:
  custom:
    planS3:
      - variables:
          - name: aws_access_key
          - name: aws_secret_key
      - step:
          script:
            - cd ${BITBUCKET_CLONE_DIR}/src/terraform/aws
            - terraform fmt
            - terraform init
            - terraform validate
            - terraform plan -var "aws_access_key=$AWS_ACCESS_KEY_ID" -var "aws_secret_key=$AWS_SECRET_ACCESS_KEY" 

    applyS3:
      - variables:
          - name: aws_access_key
          - name: aws_secret_key
      - step:
          script:
            - cd ${BITBUCKET_CLONE_DIR}/src/terraform/aws
            - ./s3.sh
    
    planApp:
      - variables:
          - name: aws_access_key
          - name: aws_secret_key
      - step:
          script:
            - cd ${BITBUCKET_CLONE_DIR}/src/terraform/karpenter
            - terraform fmt
            - terraform init
            - terraform validate
            - terraform plan -var "aws_access_key=$AWS_ACCESS_KEY_ID" -var "aws_secret_key=$AWS_SECRET_ACCESS_KEY" 

    applyApp:
      - variables:
          - name: aws_access_key
          - name: aws_secret_key
      - step:
          script:
            - cd ${BITBUCKET_CLONE_DIR}/src/terraform/karpenter
            - ./karpenter.sh 
    