[[redirects]]
    from = '/api/download'
    to = '/.netlify/functions/getVideo'
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[functions]
    directory = "api"

[dev]
    command = "yarn start"
    targetPort = 3000
    port = 8888
    publish = "build"