# File này chỉ chạy 1 lần duy nhất, toàn bộ bản đồ sẽ được in rõ

with open('../test/maze01.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   x   xx xx        x\n')
    outfile.write('x     x     xxxxxxxxxx\n')
    outfile.write('x x    xx  xxxx xxx xx\n')
    outfile.write('  x   x x xx   xxxx  x\n')
    outfile.write('x          xx  xx  x x\n')
    outfile.write('xxxxxxx x      xx  x x\n')
    outfile.write('xxxxxxxxx  x x  xx   x\n')
    outfile.write('x          x x Sx x  x\n')
    outfile.write('xxxxx x  x x x     x x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')


with open('../test/maze02.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   x   xx xx        x\n')
    outfile.write('x     x     xxx xxxxxx\n')
    outfile.write('x x     x  xxx  xxx xx\n')
    outfile.write('  x   x x xx   xxxx  x\n')
    outfile.write('x       x  xx  xx  x x\n')
    outfile.write('xxxxxxx x      xx  x x\n')
    outfile.write('xxxxxxxxx  x x  xx   x\n')
    outfile.write('x          x x Sx x  x\n')
    outfile.write('xxxxx x  x x x       x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')

with open('../test/maze03.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   x   xx xx         x           x\n')
    outfile.write('x     x     xxx xxxxx x           x\n')
    outfile.write('x x     x  xxx  xxxxxxxxxxxxxxxx  x\n')
    outfile.write('  x   x x xx   xxxx   x           x\n')
    outfile.write('x       x  xx  xx  x  x    xxxxx xx\n')
    outfile.write('xxxxxxx x      xx  x              x\n')
    outfile.write('xxxxxxxxx  x x  xxxxxxxxxxxxxxxx xx\n')
    outfile.write('x          x x  x x    x    x     x\n')
    outfile.write('xxxxx x  x x x         x    x   S x\n')
    outfile.write('xxxxxxx x      xx  xxxxxxxxxx     x\n')
    outfile.write('xxxxxxxxx  x x  xx                x\n')
    outfile.write('x          x x  x x     xxxxx     x\n')
    outfile.write('xxxxx x  x x x               xxxx x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

with open('../test/maze04.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   x   xx xx       Sx\n')
    outfile.write('x     x     xxx xxxxxx\n')
    outfile.write('x x     x  xxx  xxx xx\n')
    outfile.write('x x   x x xx   xxxx  x\n')
    outfile.write('x       x  xx  xx  x x\n')
    outfile.write('xxxxxxx x      xx  x x\n')
    outfile.write('xxxxxxxxx  x x  xx   x\n')
    outfile.write('           x x  x x  x\n')
    outfile.write('xxxxx x  x x x       x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')

with open('../test/maze05.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   x   xx xxS          x\n')
    outfile.write('x     x     xxxxxxxxx xxx\n')
    outfile.write('x x     x  xxx  xxx x   x\n')
    outfile.write('x x   x x xx   xxxx     x\n')
    outfile.write('x       x  xx  xx  x    x\n')
    outfile.write('  xxxxx x      xx  x    x\n')
    outfile.write('xxxxxxxxx  x x  xx x    x\n')
    outfile.write('x          x x  x x     x\n')
    outfile.write('xxxxx x  x x x          x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxx')

with open('../test/maze06.txt', 'w') as outfile:
    outfile.write('2\n')
    outfile.write('3 6 -3\n')
    outfile.write('5 14 -1\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   x   xx xx        x\n')
    outfile.write('x     x     xxxxxxxxxx\n')
    outfile.write('x x   +xx  xxxx xxx xx\n')
    outfile.write('  x   x x xx   xxxx  x\n')
    outfile.write('x          xx +xx  x x\n')
    outfile.write('xxxxxxx x      xx  x x\n')
    outfile.write('xxxxxxxxx  x x  xx   x\n')
    outfile.write('x          x x Sx x  x\n')
    outfile.write('xxxxx x  x x x     x x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')

with open('../test/maze07.txt', 'w') as outfile:
    outfile.write('5\n')
    outfile.write('2 2 -2\n')
    outfile.write('5 4 -2\n')
    outfile.write('5 10 -3\n')
    outfile.write('4 19 -2\n')
    outfile.write('9 21 -1\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   x   xx xxS          x\n')
    outfile.write('x +   x     xxxxxxxxx xxx\n')
    outfile.write('x x     x  xxx  xxx x   x\n')
    outfile.write('x x   x x xx   xxxx+    x\n')
    outfile.write('x   +   x +xx  xx  x    x\n')
    outfile.write('  xxxxx x      xx  x    x\n')
    outfile.write('xxxxxxxxx  x x  xx x    x\n')
    outfile.write('x          x x  x x     x\n')
    outfile.write('xxxxx x  x x x       +  x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxx')

with open('../test/maze08.txt', 'w') as outfile:
    outfile.write('10\n')
    outfile.write('2 2 -2\n')
    outfile.write('3 3 -1\n')
    outfile.write('8 6 -1\n')
    outfile.write('6 7 -3\n')
    outfile.write('9 10 -1\n')
    outfile.write('9 19 -2\n')
    outfile.write('13 23 -3\n')
    outfile.write('6 24 -1\n')
    outfile.write('1 29 -2\n')
    outfile.write('8 29 -2\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   x   xx xx         x      +    x\n')
    outfile.write('x +   x     xxx xxxxx x           x\n')
    outfile.write('x x+    x  xxx  xxxxxxxxxxxxxxxx  x\n')
    outfile.write('  x   x x xx   xxxx   x           x\n')
    outfile.write('x       x  xx  xx  x  x    xxxxx xx\n')
    outfile.write('xxxxxxx+x      xx  x    +         x\n')
    outfile.write('xxxxxxxxx  x x  xxxxxxxxxxxxxxxx xx\n')
    outfile.write('x     +    x x  x x    x    x+    x\n')
    outfile.write('xxxxx x  x+x x     +   x    x   S x\n')
    outfile.write('xxxxxxx x      xx  xxxxxxxxxx     x\n')
    outfile.write('xxxxxxxxx  x x  xx                x\n')
    outfile.write('x          x x  x x     xxxxx     x\n')
    outfile.write('xxxxx x  x x x         +     xxxx x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
